### ISSUE TITLE
Error on api updates

### ISSUE THREAD

**Issue by tyler274** [eve-seat/seat#338]
Last status: Started AssetList Update
Error: 0: Error while reading line from the server [tcp://127.0.0.1:6379]
File: /home/bovril/seat/vendor/predis/predis/lib/Predis/Connection/AbstractConnection.php:141
Trace: #0 /home/bovril/seat/vendor/predis/predis/lib/Predis/Connection/StreamConnection.php(208): Predis\Connection\AbstractConnection->onConnectionError('Error while rea...')
#1 /home/bovril/seat/vendor/predis/predis/lib/Predis/Connection/AbstractConnection.php(130): Predis\Connection\StreamConnection->read()
#2 /home/bovril/seat/vendor/predis/predis/lib/Predis/Connection/AbstractConnection.php(122): Predis\Connection\AbstractConnection->readResponse(Object(Predis\Command\KeyDelete))
#3 /home/bovril/seat/vendor/predis/predis/lib/Predis/Client.php(246): Predis\Connection\AbstractConnection->executeCommand(Object(Predis\Command\KeyDelete))
#4 /home/bovril/seat/vendor/predis/predis/lib/Predis/Client.php(228): Predis\Client->executeCommand(Object(Predis\Command\KeyDelete))
#5 /home/bovril/seat/vendor/laravel/framework/src/Illuminate/Cache/RedisStore.php(120): Predis\Client->__call('del', Array)
#6 /home/bovril/seat/vendor/laravel/framework/src/Illuminate/Cache/RedisStore.php(120): Predis\Client->del('laravel:api_loc...')
#7 [internal function]: Illuminate\Cache\RedisStore->forget('api_lock_3c1264...')
#8 /home/bovril/seat/vendor/laravel/framework/src/Illuminate/Cache/Repository.php(279): call_user_func_array(Array, Array)
#9 [internal function]: Illuminate\Cache\Repository->__call('forget', Array)
#10 [internal function]: Illuminate\Cache\Repository->forget('api_lock_3c1264...')
#11 /home/bovril/seat/bootstrap/compiled.php(7776): call_user_func_array(Array, Array)
#12 /home/bovril/seat/bootstrap/compiled.php(3176): Illuminate\Support\Manager->__call('forget', Array)
#13 /home/bovril/seat/bootstrap/compiled.php(3176): Illuminate\Cache\CacheManager->forget('api_lock_3c1264...')
#14 /home/bovril/seat/app/eveapi/BaseAPI.php(343): Illuminate\Support\Facades\Facade::__callStatic('forget', Array)
#15 /home/bovril/seat/app/eveapi/BaseAPI.php(343): Illuminate\Support\Facades\Cache::forget('api_lock_3c1264...')
#16 /home/bovril/seat/app/eveapi/character/CharacterAssetList.php(140): Seat\EveApi\BaseApi::unlockCall('3c1264db16a574d...')
#17 /home/bovril/seat/app/queues/full/EveCharacter.php(68): Seat\EveApi\Character\AssetList::Update('3565888', 'XIKzAzYd5BuNzGG...')
#18 /home/bovril/seat/vendor/laravel/framework/src/Illuminate/Queue/Jobs/Job.php(96): Seat\EveQueues\Full\Character->fire(Object(Illuminate\Queue\Jobs\RedisJob), Array)
#19 /home/bovril/seat/vendor/laravel/framework/src/Illuminate/Queue/Jobs/RedisJob.php(46): Illuminate\Queue\Jobs\Job->resolveAndFire(Array)
#20 /home/bovril/seat/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(119): Illuminate\Queue\Jobs\RedisJob->fire()
#21 /home/bovril/seat/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(71): Illuminate\Queue\Worker->process('redis', Object(Illuminate\Queue\Jobs\RedisJob), '1', '0')
#22 /home/bovril/seat/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(64): Illuminate\Queue\Worker->pop(NULL, 'default', '0', '128', '3', '1')
#23 /home/bovril/seat/vendor/laravel/framework/src/Illuminate/Console/Command.php(108): Illuminate\Queue\Console\WorkCommand->fire()
#24 /home/bovril/seat/vendor/symfony/console/Symfony/Component/Console/Command/Command.php(241): Illuminate\Console\Command->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#25 /home/bovril/seat/vendor/laravel/framework/src/Illuminate/Console/Command.php(96): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#26 /home/bovril/seat/vendor/symfony/console/Symfony/Component/Console/Application.php(887): Illuminate\Console\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#27 /home/bovril/seat/vendor/symfony/console/Symfony/Component/Console/Application.php(191): Symfony\Component\Console\Application->doRunCommand(Object(Illuminate\Queue\Console\WorkCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#28 /home/bovril/seat/vendor/symfony/console/Symfony/Component/Console/Application.php(121): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#29 /home/bovril/seat/artisan(59): Symfony\Component\Console\Application->run()
#30 {main}
Previous:

**Comment by tyler274** [comment]
Happening on many of the jobs queued, but not all

**Comment by tyler274** [comment]
Updating the redis server from 2.2.2 to 2.2.8 seemed to fix whatever the issue was... closing for the time being.
